name: Preview Deployment

on:
  push:
    branches-ignore: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  preview:
    runs-on: ubuntu-latest
    environment: preview
    steps:
    - uses: actions/checkout@v4
    
    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18.x'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Start server
      run: |
        node app.js &
        sleep 2
      env:
        PORT: 3099
    
    - name: Run tests
      run: npm run test:unix
    
    - name: Install Vercel CLI
      run: npm install --global vercel@latest
      
    - name: Pull Vercel Environment Information
      run: vercel pull --yes --environment=preview --token=${{ secrets.VERCEL_TOKEN }} --project=prj_mnO51dQZSmX1c83EMJfn7IAARaCG
      
    - name: Build Project Artifacts
      run: vercel build --token=${{ secrets.VERCEL_TOKEN }} --project=prj_mnO51dQZSmX1c83EMJfn7IAARaCG
      
    - name: Deploy to Vercel Preview
      id: deploy
      run: echo "url=$(vercel deploy --prebuilt --token=${{ secrets.VERCEL_TOKEN }} --project=prj_mnO51dQZSmX1c83EMJfn7IAARaCG)" >> $GITHUB_OUTPUT

    - name: Comment Preview URL
      if: github.event_name == 'pull_request'
      uses: actions/github-script@v6
      with:
        script: |
          github.rest.issues.createComment({
            owner: 'gblanc25',
            repo: 'faleproxy',
            issue_number: context.issue.number,
            body: `✨ Preview deployment is ready! You can view it at: ${process.env.DEPLOY_URL}`
          })
      env:
        DEPLOY_URL: ${{ steps.deploy.outputs.url }}

    - name: Output Preview URL
      if: github.event_name == 'push'
      run: |
        echo "Preview deployment is ready at: ${{ steps.deploy.outputs.url }}"
